Repository UB-ES-2024-C2/UB_Reads, pull requests merged in 2024-12, with the labels that each got.

#225 US15 [Aplicar logica dades]
  UBReads_backend/database.db
  UBReads_frontend/.DS_Store
  UBReads_frontend/src/components/Books/BookView.jsx
  UBReads_frontend/src/components/Followers/FollowersView.jsx
  UBReads_frontend/src/components/Home/HomePage.jsx
  UBReads_frontend/src/components/Home/HomeView.jsx
  UBReads_frontend/src/components/Library/LibraryView.jsx
  UBReads_frontend/src/components/Profile/ProfileView.jsx
  UBReads_frontend/src/components/Search/SearchView.jsx
  UBReads_frontend/src/components/common/Nav.jsx
  UBReads_frontend/src/services/BookService.js
  UBReads_frontend/src/services/FollowerService.js
  UBReads_frontend/src/services/LibraryService.js
  UBReads_frontend/src/services/UserService.js
Labels: UI, enhancement

#227 sprint3/US9/us9-dev
  UBReads_backend/app/controllers/book_user_controller.py
  UBReads_backend/app/core/models.py
  UBReads_backend/app/routers/book_user_router.py
  UBReads_backend/app/schemas/user_book.py
  UBReads_backend/database.db
  UBReads_frontend/src/components/Books/Book.test.jsx
  UBReads_frontend/src/components/Books/BookView.jsx
  UBReads_frontend/src/components/Library/LibraryView.jsx
  UBReads_frontend/src/components/Search/SearchBookCard.jsx
  UBReads_frontend/src/components/common/BookRating.jsx
  UBReads_frontend/src/components/common/BookRatingAvg.jsx
  UBReads_frontend/src/components/common/BookRatingUser.jsx
  UBReads_frontend/src/components/index.js
  UBReads_frontend/src/services/BookService.js
  UBReads_frontend/src/services/LibraryService.js
Labels: UI, enhancement, refactoring

#230 sprint3/US12/frontend/feature/pop-up
  UBReads_frontend/src/components/Books/BookView.jsx
  UBReads_frontend/src/components/Search/SearchBookCard.jsx
  UBReads_frontend/src/components/common/Nav.jsx
  UBReads_frontend/src/services/LibraryService.js
Labels: UI

#226 US15 [Omplir pàgina d'inici]
  UBReads_frontend/.DS_Store
  UBReads_frontend/src/components/Books/BookView.jsx
  UBReads_frontend/src/components/Followers/FollowersView.jsx
  UBReads_frontend/src/components/Home/HomePage.jsx
  UBReads_frontend/src/components/Home/HomeView.jsx
  UBReads_frontend/src/components/Library/LibraryView.jsx
  UBReads_frontend/src/components/Profile/ProfileView.jsx
  UBReads_frontend/src/components/Search/SearchView.jsx
  UBReads_frontend/src/components/common/BookRatingAvg.jsx
  UBReads_frontend/src/components/common/BookRatingUser.jsx
  UBReads_frontend/src/components/common/Nav.jsx
  UBReads_frontend/src/components/index.js
  UBReads_frontend/src/services/BookService.js
  UBReads_frontend/src/services/FollowerService.js
  UBReads_frontend/src/services/LibraryService.js
  UBReads_frontend/src/services/UserService.js
Labels: UI, enhancement

#232 Added checkbox
  UBReads_frontend/src/components/Books/BookView.jsx
  UBReads_frontend/src/services/LibraryService.js
Labels: UI

#236 Can filter from biblioteca
  UBReads_frontend/src/components/Books/BookView.jsx
  UBReads_frontend/src/components/Library/LibraryView.jsx
  UBReads_frontend/src/components/Search/SearchBookCard.jsx
  UBReads_frontend/src/components/common/BookRatingAvg.jsx
  UBReads_frontend/src/services/LibraryService.js
Labels: UI, enhancement

#235 US16 [Pàgina de seguits 2.0]
  UBReads_frontend/.env
  UBReads_frontend/.env.preproduction
  UBReads_frontend/.env.production
  UBReads_frontend/src/components/Books/BookView.jsx
  UBReads_frontend/src/components/Followers/FollowersBookList.jsx
  UBReads_frontend/src/components/Followers/FollowersView.jsx
  UBReads_frontend/src/components/Followers/userCard.jsx
  UBReads_frontend/src/components/Followers/userList.jsx
  UBReads_frontend/src/components/Home/HomePage.jsx
  UBReads_frontend/src/components/Home/HomeView.jsx
  UBReads_frontend/src/components/Library/LibraryView.jsx
  UBReads_frontend/src/components/Profile/ProfileView.jsx
  UBReads_frontend/src/components/Search/SearchView.jsx
  UBReads_frontend/src/components/common/Nav.jsx
  UBReads_frontend/src/components/index.js
  UBReads_frontend/src/main.jsx
  UBReads_frontend/src/services/BookService.js
  UBReads_frontend/src/services/FollowerService.js
  UBReads_frontend/src/services/LibraryService.js
Labels: UI, enhancement

#238 sprint3/US12/us12-dev
  UBReads_frontend/src/components/Books/BookView.jsx
  UBReads_frontend/src/components/Followers/FollowersView.jsx
  UBReads_frontend/src/components/Library/LibraryView.jsx
  UBReads_frontend/src/components/Search/SearchBookCard.jsx
  UBReads_frontend/src/components/common/BookRatingAvg.jsx
  UBReads_frontend/src/components/index.js
  UBReads_frontend/src/services/LibraryService.js
Labels: UI, enhancement, refactoring

#249 deploy bug fix
  package-lock.json
  package.json
Labels: bug
